---
    - name: metricbeat
      hosts: webservers
      become: true
      tasks:
       - name: Download Metric
         shell: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb
       - name: Install Metric
         shell: sudo dpkg -i metricbeat-7.6.1-amd64.deb
       - name: Trandfer file
         copy:
          src: /etc/ansible/files/metric.yml
          dest: /etc/metricbeat/metricbeat.yml
       - name: Enable Metricbeat Module
         shell: sudo metricbeat modules enable docker
       - name: Metricbeat setup
         shell: sudo metricbeat setup
       - name: Metric
         shell: sudo service metricbeat start